name: Build and Deploy to Azure Blob Storage

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: 'pnpm'

      - name: Enable Corepack for pnpm
        run: corepack enable && pnpm -v

      - name: Install Dependencies
        run: pnpm install

      - name: Build Project
        run: pnpm build

      - name: Upload to Azure Blob Storage
        uses: Azure/azcopy-actions@v1
        with:
          # Connection string format: "BlobEndpoint=https://[account].blob.core.windows.net/;SharedAccessSignature=[sas_token]"
          connection_string: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
          source: './app/dist/'
          destination: 'https://${{ secrets.AZURE_STORAGE_ACCOUNT }}.blob.core.windows.net/${{ secrets.AZURE_STORAGE_CONTAINER }}'
