name: Build and Deploy to Azure Blob Storage

on:
  push:
    branches: [ "master" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: 'pnpm'

      - name: Enable Corepack for pnpm
        run: corepack enable && pnpm -v

      - name: Install Dependencies
        run: pnpm install

      - name: Build Project
        run: pnpm build

      - name: Verify Build Output
        run: ls -la ./app/dist

      - name: Setup Azure CLI
        uses: azure/CLI@v1
        with:
          inline-script: |
            az --version
            azcopy --version

      - name: Upload to Azure Blob Storage
        run: |
          azcopy copy "./app/dist" \
          "https://${{ secrets.AZURE_STORAGE_ACCOUNT }}.blob.core.windows.net/${{ secrets.AZURE_STORAGE_CONTAINER }}${{ secrets.AZURE_STORAGE_SAS_TOKEN }}" \
          --recursive
